.PHONY: help

run:
	# Execute subset.go
	go run ./subset.go
help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "This makefile has one target: run."
	@echo "It executes the subset.go program that demonstrates subset in Go."
	@echo ""
	@echo "Available target:"
	@echo "  run  - Run the subset.go program"
	@echo ""